apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ=  # Base64 encoded "password"
  MYSQL_REPLICATION_USER: cmVwbGljYQ==  # Base64 encoded "replica"
  MYSQL_REPLICATION_PASSWORD: cmVwbGljYXBhc3M=  # Base64 encoded "replicapassword"